function [ to_few_beads ] = BH_refine_on_beads(baseName,NX,NY,thickness,pixelSize,bead_diameter)

% baseName='SARS_nCov_0320_05';
% NX=3838;
% NY=3710;
% thickness=3000;
% 
% pixelSize = 1.36;
% bead_diameter = 100;

bead_size=bead_diameter./pixelSize;

pixelSizeInNanometers=pixelSize./10;
ptSizeX=128;
ptSizeY=128;

first_run = true;
to_few_beads = false;
% So it can be tested if desired, but an initial look did not seem
% promising. The x_tilt produces resonable results that look a little more
% contrasty, but I think it is a low-pass effect. The x_stretch does all
% kinds of weird shit.
x_tilt_option = [0,3,0,3];
x_stretch_option = [0,3,0,3];

for imageBinning = [15:-2:5]
  
  if first_run 
    input_name=baseName;
    output_name=sprintf('%s_%d',baseName,imageBinning);  
    last_binning=imageBinning;
    first_run=false;
    xTiltOption = '-XAXISTILT 0.0 ';
    z_factor_file = '';
    local_file = sprintf('-LOCALFILE %s.local ',input_name)
  else
    input_name=sprintf('%s_%d',baseName,last_binning);  
    output_name=sprintf('%s_%d',baseName,imageBinning); 
    last_binning=imageBinning;
    xTiltOption = sprintf('-XTILTFILE %s.Xtlt ',input_name);
    z_factor_file = sprintf('-ZFACTORFILE %s.Zfactor ', input_name);
    if isempty(doLocal)
      local_file = '';
    else
      local_file = sprintf(' -LOCALFILE %s.local ' , input_name);     
    end
  end

  [ fail ] = system(sprintf( ...
  ['newstack ', ...
    '-InputFile  %s.fixed ', ...
    '-OutputFile	%s_3dfind.ali ', ...
    '-TransformFile	%s.xf ', ...
    '-ImagesAreBinned	1.0 ', ...
    '-BinByFactor %d'],baseName,output_name,input_name,imageBinning)); 

  if (fail) 
    error('asdf')  
  end

  if ( imageBinning >= 9)

  [ fail ] = system(sprintf([...
  'tilt ' ...
    '-InputProjections %s_3dfind.ali ' ...
    '-OutputFile %s_3dfind.rec ' ...
    '-TILTFILE %s.tlt ' ...
    '-IMAGEBINNED %d ' ...
    '-THICKNESS %d ' ...
    '-RADIAL 0.35,0.035 ' ...
    '-FalloffIsTrueSigma 1 ' ...
    '%s ' ...
    '-LOG 0.0 ' ...
    '-SCALE 0.0,250.0 ' ...
    '-MODE 2 ' ...
    '-UseGPU 0 ' ...
    '-ActionIfGPUFails 1,2 ' ...
    '-OFFSET 0.0 ' ...
    '-SHIFT 0.0 0.0 ' ...
    '-PERPENDICULAR ' ...
    '-FULLIMAGE %d,%d %s %s'],output_name,output_name,...
                        input_name,imageBinning,thickness,...
                        xTiltOption,NX,NY,local_file,z_factor_file));

  if (fail) 
    error('asdf')  
  end
  
  [ fail ] = system(sprintf([...
  'findbeads3d ' ...
    '-InputFile	%s_3dfind.rec ' ...
    '-OutputFile	%s_3dfind.mod ' ...
    '-BeadSize	%f ' ...
    '-MinRelativeStrength	0.05 ' ...
    '-StorageThreshold	0.0 ' ...
    '-FallbackThresholds 0.1,0.1 ' ...
    '-MinSpacing	0.5 ' ...
    '-BinningOfVolume	%d'], ...
    output_name,output_name,bead_size,imageBinning ...
    ));

    if (fail) 
      error('asdf')  
    end
    
  [ fail ] = system(sprintf([...
    'tilt ' ...
    '-InputProjections %s_3dfind.ali ' ...
    '-OutputFile %s.erase ' ...
    '-IMAGEBINNED %d ' ...
    '-TILTFILE %s.tlt ' ...
    '-THICKNESS %d ' ...
    '-RADIAL 0.35,0.035 ' ...
    '-FalloffIsTrueSigma 1 ' ...
    '%s ' ...
    '-LOG 0.0 ' ...
    '-SCALE 0.0,250.0 ' ...
    '-UseGPU 0 ' ...
    '-ActionIfGPUFails 1,2 ' ...
    '-OFFSET 0.0 ' ...
    '-SHIFT 0.0,0.0 ' ...
    '-ProjectModel %s_3dfind.mod ' ...
    '-FULLIMAGE %d,%d ' ...
    '-PERPENDICULAR  ' ...
    '-MODE 2 %s %s'], output_name,output_name,imageBinning,...
                input_name,thickness,...
                xTiltOption,output_name,NX,NY,local_file,z_factor_file));

    if (fail) 
      error('asdf')  
    end
  
  else
    
  [ fail ] = system(sprintf([...
  'imodtrans -2 %s.tltxf_nonScaled %s.erase ' ...
  '%s.erase'], input_name,input_name,output_name));
    if (fail) 
      error('asdf')  
    end
  end

  
  [ fail ] = system(sprintf([...
  'beadtrack ' ...
    '-InputSeedModel %s.erase ' ...
    '-OutputModel %s_beadtrack.fid ' ...
    '-ImageFile %s_3dfind.ali ' ...
    '-ImagesAreBinned %d ' ...
    '-PixelSize %f ' ...
    '-BeadDiameter %f ' ...
    '-RoundsOfTracking 3 ' ...
    '-BoxSizeXandY  %d,%d ' ...
    '-MinBeadsInArea 5 ' ...
    '-MinOverlapBeads 1 ' ...
    '-UnsplitFirstRound ' ...
    '-LocalAreaTracking ' ...
    '-LocalAreaTargetSize %d ' ...
    '-RotationAngle 0.0 ' ...
    '-TiltFile %s.tlt ' ...
    '-TiltDefaultGrouping 5 ' ...
    '-MagDefaultGrouping 1 ' ...
    '-RotDefaultGrouping 1 ' ...
    '-LowPassCutoffInverseNm 0.71 '], output_name,output_name,output_name,imageBinning,...
    pixelSizeInNanometers,bead_size,ptSizeX,ptSizeY,floor(512/imageBinning),...
    input_name ...
    ));
  
    if (fail)       
      error('asdf')  
    end
    

    [~, nBeads] =   BH_fitBeads(pixelSize,bead_diameter,imageBinning,...
                    sprintf('%s_3dfind.ali',output_name),...
                    sprintf('%s_beadtrack.fid',output_name),...
                    sprintf('%s_fit.fid',output_name)...
                    );
                  
      
  

  if (nBeads < 5)
    to_few_beads = true;
    return;
  end
  
  if (nBeads < 11)
    doLocal = '';
  else
    doLocal =  '-LocalAlignments	';
  end

  

  
  [ fail ] = system(sprintf([...
  'tiltalign ' ...
    '-ModelFile	%s_fit.fid ' ...
    '-ImageFile	%s_3dfind.ali ' ...
    '-ImagesAreBinned	%d ' ...
    '-OutputModelFile	%s.3dmod ' ...
    '-OutputResidualFile	%s.resid ' ...
    '-OutputFidXYZFile	%sfid.xyz ' ...
    '-OutputTiltFile	%s.tlt ' ...
    '-OutputTransformFile	%s.tltxf_nonScaled ' ...
    '-OutputXAxisTiltFile %s.Xtlt ' ...
    '-OutputZFactorFile %s.Zfactor ' ...
    '-RotationAngle	0.0 ' ...
    '-TiltFile	%s.tlt ' ...
    '-RotOption	1 ' ...
    '-RotDefaultGrouping	3 ' ...
    '-TiltOption 5 ' ...
    '-TiltDefaultGrouping	3 ' ...
    '-XTiltOption %d ' ...
    '-XTiltDefaultGrouping %d ' ...
    '-XStretchOption %d ' ...
    '-XStretchDefaultGrouping %d ' ...
    '-MagOption	1 ' ...
    '-MagDefaultGrouping	3 ' ...
    '-BeamTiltOption	0 ' ...
    '-ResidualReportCriterion	1.0 ' ...
    '-SurfacesToAnalyze	0 ' ...
    '-RobustFitting	1 ' ...
    '-MetroFactor	0.25 ' ...
    '-MaximumCycles	1000 ' ...
    '-KFactorScaling	1.0 ' ...
    '-NoSeparateTiltGroups	2 ' ...
    '-AxisZShift	1000 ' ...
    '-ShiftZFromOriginal      1 ' ...
    '-OutputLocalFile	%s.local ' ...
    '-TargetPatchSizeXandY	%d,%d ' ...
    '-MinSizeOrOverlapXandY	0.3,0.3 ' ...
    '-MinFidsTotalAndEachSurface	6,3 ' ...
    '-LocalRotOption	1 ' ...
    '-LocalRotDefaultGrouping	6 ' ...
    '-LocalTiltOption	0 ' ...
    '-LocalTiltDefaultGrouping	3 ' ...
    '-LocalXTiltOption %d ' ...
    '-LocalXTiltDefaultGrouping %d ' ...
    '-LocalXStretchOption %d ' ...
    '-LocalXStretchDefaultGrouping %d ' ...
    '-LocalMagOption	1 ' ...
    '-LocalMagDefaultGrouping	7  ' ...
    '-AngleOffset 0.0 %s > tiltAlign_%s.log'],...
    output_name,output_name,imageBinning,...
    output_name,output_name,output_name,output_name,output_name,output_name,...
    output_name,input_name,x_tilt_option(1:2),x_stretch_option(1:2),output_name,ptSizeX,ptSizeY,...
    x_tilt_option(3:4), x_stretch_option(3:4),doLocal,output_name));
  
  if (fail) 
    error('asdf')  
  end
  
  [ fail ] = system(sprintf('xfproduct -scale 1,%d %s.xf %s.tltxf_nonScaled %s.xf', imageBinning,input_name,output_name,output_name));
      
  if (fail) 
    error('asdf')  
  end
  
 end
end
