#!/bin/bash

#Please modify this line to point to the text file in your MCR root
#where you pasted the lines suggested to add to LD_LIBRARY_PATH during install.
#MCR_BASH="/work/thirdParty/MATLAB/mcr_bash.sh"
MCR_BASH=""


#Please modify this line to point to the install for emClarity binary
#emClarity_ROOT=/work/emClarity
emClarity_ROOT=""




if [ -f ${MCR_BASH} ]; then
  source ${MCR_BASH}
else
  echo "Did not find your mcr_bash file, did you fill it in above?"
  exit 1
fi

if [ ! -f ${emClarity_ROOT}/emClarity_2016b ]; then
  echo "Did not find the binary on the path, did you fill it in above?"
  exit 1
fi

argList=6d10727 
while [ $# -gt 0 ]; do
  token=$1
  argList="${argList} ${token}"
  shift
done

${emClarity_ROOT}/emClarity_2016b ${argList}
